"""
business_area.py — Server-side mirror of `src/utils/businessArea.js`.

Single source of truth on the back-end for the rule:

    location_code  →  business_area_code

Both halves of the system MUST agree. The front-end value of
`business_area_code` is display-only; the back-end recomputes it on save and
NEVER trusts the client.

Whitelisted mainland China codes are loaded from
`backend/app/data/mainland_locations.json` (generated by
`scripts/build-mainland-locations.js`). Run that script after upgrading
the npm `@province-city-china/data` package.
"""

from __future__ import annotations

import json
import os
from typing import Optional


# ── Business-area taxonomy (mirrors front-end BUSINESS_AREAS) ────────────────

BUSINESS_AREAS: dict[str, dict[str, str]] = {
    "GLOBAL":        {"code": "GLOBAL",        "name": "Global"},
    "REMOTE":        {"code": "REMOTE",        "name": "Remote"},
    "GREAT_CHINA":   {"code": "GREAT_CHINA",   "name": "Great China"},
    "EAST_CHINA":    {"code": "EAST_CHINA",    "name": "East China"},
    "NORTH_CHINA":   {"code": "NORTH_CHINA",   "name": "North China"},
    "SOUTH_CHINA":   {"code": "SOUTH_CHINA",   "name": "South China"},
    "WEST_CHINA":    {"code": "WEST_CHINA",    "name": "West China"},
    "CENTRAL_CHINA": {"code": "CENTRAL_CHINA", "name": "Central China"},
    "HONG_KONG":     {"code": "HONG_KONG",     "name": "Hong Kong"},
    "TAIWAN":        {"code": "TAIWAN",        "name": "Taiwan"},
    "OVERSEAS":      {"code": "OVERSEAS",      "name": "Overseas"},
}

# ── Mainland-China province-prefix → business-area map ──────────────────────
# Mirrors the front-end PROVINCE_TO_AREA in src/utils/businessArea.js.

_PROVINCE_TO_AREA: dict[str, str] = {
    # North China
    "11": "NORTH_CHINA", "12": "NORTH_CHINA", "13": "NORTH_CHINA",
    "14": "NORTH_CHINA", "15": "NORTH_CHINA",
    # Northeast → grouped under North China (no NORTHEAST_CHINA bucket in spec)
    "21": "NORTH_CHINA", "22": "NORTH_CHINA", "23": "NORTH_CHINA",
    # East China
    "31": "EAST_CHINA",  "32": "EAST_CHINA",  "33": "EAST_CHINA",
    "34": "EAST_CHINA",  "35": "EAST_CHINA",  "36": "EAST_CHINA",
    "37": "EAST_CHINA",
    # Central China
    "41": "CENTRAL_CHINA", "42": "CENTRAL_CHINA", "43": "CENTRAL_CHINA",
    # South China
    "44": "SOUTH_CHINA", "45": "SOUTH_CHINA", "46": "SOUTH_CHINA",
    # West China (southwest + northwest)
    "50": "WEST_CHINA", "51": "WEST_CHINA", "52": "WEST_CHINA",
    "53": "WEST_CHINA", "54": "WEST_CHINA",
    "61": "WEST_CHINA", "62": "WEST_CHINA", "63": "WEST_CHINA",
    "64": "WEST_CHINA", "65": "WEST_CHINA",
}

# Province prefixes the system explicitly REJECTS as mainland location codes.
_FORBIDDEN_MAINLAND_PREFIXES = frozenset({"71", "81", "82"})


# ── Overseas country whitelist (mirrors front-end OVERSEAS_COUNTRIES) ───────
# Adding a country: also add it in src/utils/overseasCountries.js. Both halves
# of the whitelist MUST stay in lock-step or validate_location_payload will
# reject codes that the front-end was happy to send.

OVERSEAS_COUNTRIES: list[dict[str, str]] = [
    # Americas
    {"code": "US", "name": "United States",  "name_zh": "美国"},
    {"code": "CA", "name": "Canada",         "name_zh": "加拿大"},
    {"code": "MX", "name": "Mexico",         "name_zh": "墨西哥"},
    {"code": "BR", "name": "Brazil",         "name_zh": "巴西"},
    {"code": "CL", "name": "Chile",          "name_zh": "智利"},
    # Europe
    {"code": "GB", "name": "United Kingdom", "name_zh": "英国"},
    {"code": "DE", "name": "Germany",        "name_zh": "德国"},
    {"code": "FR", "name": "France",         "name_zh": "法国"},
    {"code": "NL", "name": "Netherlands",    "name_zh": "荷兰"},
    {"code": "BE", "name": "Belgium",        "name_zh": "比利时"},
    {"code": "IT", "name": "Italy",          "name_zh": "意大利"},
    {"code": "ES", "name": "Spain",          "name_zh": "西班牙"},
    {"code": "PL", "name": "Poland",         "name_zh": "波兰"},
    # Asia
    {"code": "JP", "name": "Japan",          "name_zh": "日本"},
    {"code": "KR", "name": "South Korea",    "name_zh": "韩国"},
    {"code": "SG", "name": "Singapore",      "name_zh": "新加坡"},
    {"code": "MY", "name": "Malaysia",       "name_zh": "马来西亚"},
    {"code": "TH", "name": "Thailand",       "name_zh": "泰国"},
    {"code": "VN", "name": "Vietnam",        "name_zh": "越南"},
    {"code": "ID", "name": "Indonesia",      "name_zh": "印度尼西亚"},
    {"code": "PH", "name": "Philippines",    "name_zh": "菲律宾"},
    {"code": "IN", "name": "India",          "name_zh": "印度"},
    # Middle East
    {"code": "AE", "name": "United Arab Emirates", "name_zh": "阿联酋"},
    {"code": "SA", "name": "Saudi Arabia",         "name_zh": "沙特阿拉伯"},
    # Oceania
    {"code": "AU", "name": "Australia",   "name_zh": "澳大利亚"},
    {"code": "NZ", "name": "New Zealand", "name_zh": "新西兰"},
    # Africa
    {"code": "ZA", "name": "South Africa", "name_zh": "南非"},
    {"code": "EG", "name": "Egypt",        "name_zh": "埃及"},
]

OVERSEAS_COUNTRY_CODES = frozenset(c["code"] for c in OVERSEAS_COUNTRIES)


# ── Mainland whitelist (loaded once from JSON) ──────────────────────────────

_DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")
_MAINLAND_FILE = os.path.normpath(os.path.join(_DATA_DIR, "mainland_locations.json"))

_MAINLAND_CODES_CACHE: Optional[frozenset[str]] = None


def _load_mainland_codes() -> frozenset[str]:
    global _MAINLAND_CODES_CACHE
    if _MAINLAND_CODES_CACHE is not None:
        return _MAINLAND_CODES_CACHE
    try:
        with open(_MAINLAND_FILE, encoding="utf-8") as fh:
            rows = json.load(fh)
    except FileNotFoundError:
        # Fail open with empty whitelist — back-end will reject every
        # mainland code, which is safer than silently allowing all of them.
        _MAINLAND_CODES_CACHE = frozenset()
        return _MAINLAND_CODES_CACHE
    codes = {r["code"] for r in rows if isinstance(r, dict) and "code" in r}
    _MAINLAND_CODES_CACHE = frozenset(codes)
    return _MAINLAND_CODES_CACHE


# ── Public helpers ──────────────────────────────────────────────────────────


def get_province_code(location_code: Optional[str]) -> Optional[str]:
    """Return the 6-digit province-level code for a mainland 6-digit input,
    or None if the input is not a 6-digit numeric string."""
    if not location_code:
        return None
    s = str(location_code)
    if len(s) != 6 or not s.isdigit():
        return None
    return s[:2] + "0000"


def is_mainland_china_code(location_code: Optional[str]) -> bool:
    """True iff `location_code` is a 6-digit numeric code whose province
    prefix is on the allowed mainland list AND the full code itself is
    present in the loaded mainland whitelist."""
    if not location_code:
        return False
    s = str(location_code)
    if len(s) != 6 or not s.isdigit():
        return False
    prefix = s[:2]
    if prefix in _FORBIDDEN_MAINLAND_PREFIXES:
        return False
    if prefix not in _PROVINCE_TO_AREA:
        return False
    return s in _load_mainland_codes()


def is_allowed_special_location_code(code: Optional[str]) -> bool:
    """True iff `code` is one of the special non-numeric location codes the
    system accepts (Global / Remote / mainland aggregate / HK / TW)."""
    return code in {"GLOBAL", "REMOTE", "CN_MAINLAND_ALL", "HK", "TW"}


def is_known_overseas_country_code(code: Optional[str]) -> bool:
    """True iff `code` is on the system's overseas-country whitelist."""
    return code in OVERSEAS_COUNTRY_CODES


def is_valid_location_code(location_code: Optional[str]) -> bool:
    """True iff `location_code` is acceptable as a job/candidate location."""
    if not location_code:
        return False
    if is_allowed_special_location_code(location_code):
        return True
    if is_known_overseas_country_code(location_code):
        return True
    if is_mainland_china_code(location_code):
        return True
    return False


def get_business_area_by_location_code(location_code: Optional[str]) -> Optional[dict]:
    """The single rule that maps `location_code` to its business area dict
    `{code, name}`. Returns None for unknown / forbidden codes."""
    if not location_code:
        return None

    if location_code == "GLOBAL":          return BUSINESS_AREAS["GLOBAL"]
    if location_code == "REMOTE":          return BUSINESS_AREAS["REMOTE"]
    if location_code == "CN_MAINLAND_ALL": return BUSINESS_AREAS["GREAT_CHINA"]
    if location_code == "HK":              return BUSINESS_AREAS["HONG_KONG"]
    if location_code == "TW":              return BUSINESS_AREAS["TAIWAN"]

    if is_known_overseas_country_code(location_code):
        return BUSINESS_AREAS["OVERSEAS"]

    if is_mainland_china_code(location_code):
        prefix = str(location_code)[:2]
        area_key = _PROVINCE_TO_AREA.get(prefix)
        if area_key:
            return BUSINESS_AREAS[area_key]

    return None


def validate_location_payload(data: Optional[dict]) -> tuple[Optional[dict], Optional[str]]:
    """Validate a client-supplied location payload.

    Required keys: location_code, location_name, location_path, location_type.

    Returns `(normalized_dict, None)` on success, or `(None, error_message)`
    on failure. The normalized dict ALWAYS uses the back-end's computed
    business_area_code/name — any value the client put there is discarded.
    """
    if not isinstance(data, dict):
        return None, "location payload must be an object"

    code = data.get("location_code")
    name = data.get("location_name")
    path = data.get("location_path")
    typ  = data.get("location_type")

    if not code: return None, "location_code is required"
    if not name: return None, "location_name is required"
    if not path: return None, "location_path is required"
    if not typ:  return None, "location_type is required"

    if not is_valid_location_code(code):
        return None, f"Unknown or forbidden location_code: {code}"

    area = get_business_area_by_location_code(code)
    if not area:
        # is_valid_location_code passed but business-area lookup failed:
        # this should be impossible — fail closed.
        return None, f"Cannot resolve business_area for location_code: {code}"

    return (
        {
            "location_code":      code,
            "location_name":      name,
            "location_path":      path,
            "location_type":      typ,
            "business_area_code": area["code"],
            "business_area_name": area["name"],
        },
        None,
    )


def location_filter_clause(column, business_area_column, location_code: str):
    """Build a SQLAlchemy filter clause for "rows whose location_code is
    semantically inside `location_code`".

    Semantics:
      - Mainland province-level code (e.g. ``310000``): match every code
        whose first 2 digits equal the input's first 2 digits (i.e. the
        whole province).
      - Mainland city-level code (e.g. ``310100``): match every code whose
        first 4 digits equal the input's first 4 digits (i.e. the whole
        city, including its districts and the city-level row itself).
      - Mainland area-level code (e.g. ``310101``): exact match.
      - ``CN_MAINLAND_ALL``: match every row whose ``business_area_code`` is
        one of the mainland buckets (Great China / East / North / South /
        West / Central). This is the only branch that goes through
        ``business_area_column``.
      - ``GLOBAL`` / ``REMOTE`` / ``HK`` / ``TW`` / overseas country code:
        exact match against ``location_code``.

    Returns a SQLAlchemy clause, or ``None`` if the input is invalid (caller
    should treat that as "do not apply this filter").
    """
    from sqlalchemy import or_, and_

    if not location_code:
        return None
    code = str(location_code).strip()
    if not code:
        return None

    # CN_MAINLAND_ALL → all mainland business areas
    if code == "CN_MAINLAND_ALL":
        mainland_areas = ["GREAT_CHINA", "EAST_CHINA", "NORTH_CHINA",
                          "SOUTH_CHINA", "WEST_CHINA", "CENTRAL_CHINA"]
        return business_area_column.in_(mainland_areas)

    # Special non-numeric codes: exact match
    if is_allowed_special_location_code(code) or is_known_overseas_country_code(code):
        return column == code

    # 6-digit mainland code: prefix match by granularity
    if len(code) == 6 and code.isdigit():
        prefix = code[:2]
        if prefix in _FORBIDDEN_MAINLAND_PREFIXES:
            return None
        if prefix not in _PROVINCE_TO_AREA:
            return None
        if code.endswith("0000"):
            # Province-level
            return column.like(f"{prefix}%")
        if code.endswith("00"):
            # City-level
            return column.like(f"{code[:4]}%")
        # Area-level (e.g. 310101)
        return column == code

    return None
